web/router.ex
defmodule Foodtimebot.Router do
  use Foodtimebot.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Foodtimebot do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    # User Registrations
    resources "/registrations", RegistrationController, only: [:new, :create]
    
    # User Logins 
    get  "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/fooditems", FooditemController
    resources "/menus", MenuController
  end

  
  # Other scopes may use custom stacks.
   scope "/api", Foodtimebot do
    
   pipe_through :api
   end
end

web/views/layout_view.ex
defmodule Foodtimebot.LayoutView do
  use Foodtimebot.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Foodtimebot!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
         <%= if logged_in?(@conn) do %>
	        <li><%= current_user(@conn).email %></li>
		<li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
		<% else %>
	    	  <%= link "Register", to: registration_path(@conn, :new) %>
		       <li><%= link "Login",    to: "/login" %></li>
		<%= end %>
          </ul>
        </nav>
        <h1> MealTimePlanner,  mealtime made easy!!!</h1>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>